Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: messages, rest_framework, staticfiles
  Apply all migrations: admin, auth, authtoken, contenttypes, movies, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying movies.0001_initial... OK
  Applying sessions.0001_initial... OK
System check identified no issues (0 silenced).
test_create_and_login_for_admin_account (kmdb.test_api.TestAccountView) ... ok
test_create_and_login_for_critic_account (kmdb.test_api.TestAccountView) ... ok
test_create_and_login_for_user_account (kmdb.test_api.TestAccountView) ... ok
test_create_user_already_exists (kmdb.test_api.TestAccountView) ... ok
test_wrong_credentials_do_not_login (kmdb.test_api.TestAccountView) ... FAIL
test_admin_or_critic_cannot_create_comment (kmdb.test_api.TestCommentReviewView) ... ok
test_create_comment_with_invalid_movie_id (kmdb.test_api.TestCommentReviewView) ... ok
test_user_can_change_a_comment_on_the_movie (kmdb.test_api.TestCommentReviewView) ... ok
test_user_can_create_comment (kmdb.test_api.TestCommentReviewView) ... ok
test_user_cannot_change_a_comment_on_the_movie_that_did_not_comment (kmdb.test_api.TestCommentReviewView) ... ok
test_create_review (kmdb.test_api.TestCriticismReviewView) ... FAIL
test_update_review (kmdb.test_api.TestCriticismReviewView) ... FAIL
test_admin_can_delete_movie (kmdb.test_api.TestMovieRetrieveDestroyView) ... ok
test_anonymous_can_filter_movies (kmdb.test_api.TestMovieRetrieveDestroyView) ... ok
test_anonymous_cannot_delete_movies (kmdb.test_api.TestMovieRetrieveDestroyView) ... ok
test_anonymous_cannot_filter_movies_with_the_invalid_movie_id (kmdb.test_api.TestMovieRetrieveDestroyView) ... ok
test_user_or_critic_cannot_delete_movies (kmdb.test_api.TestMovieRetrieveDestroyView) ... ok
test_admin_can_create_movie (kmdb.test_api.TestMovieView) ... ok
test_critic_or_user_cannot_create_movie (kmdb.test_api.TestMovieView) ... ok
test_filter_movies_with_the_filter_request (kmdb.test_api.TestMovieView) ... ok
test_genre_or_classification_cannot_repet (kmdb.test_api.TestMovieView) ... ok
test_output_format_data (kmdb.test_api.TestMovieView) ... ok

======================================================================
FAIL: test_wrong_credentials_do_not_login (kmdb.test_api.TestAccountView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keller/dev/projects/kenzie-academy/q4/python/django/assignments/kmdb/kmdb/test_api.py", line 966, in test_wrong_credentials_do_not_login
    self.assertEqual(response.status_code, 401)
AssertionError: 400 != 401

======================================================================
FAIL: test_create_review (kmdb.test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keller/dev/projects/kenzie-academy/q4/python/django/assignments/kmdb/kmdb/test_api.py", line 1097, in test_create_review
    self.assertEqual(response.status_code, 404)
AssertionError: 400 != 404

======================================================================
FAIL: test_update_review (kmdb.test_api.TestCriticismReviewView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keller/dev/projects/kenzie-academy/q4/python/django/assignments/kmdb/kmdb/test_api.py", line 1230, in test_update_review
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

----------------------------------------------------------------------
Ran 22 tests in 4.999s

FAILED (failures=3)
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
